In [1]:
import numpy as np

<h3>Array concatenation and splitting<h3>

In [2]:
x = np.array([3, 2, 1])
y = np.array([1, 2, 3])
np.concatenate([x, y])

array([3, 2, 1, 1, 2, 3])

In [3]:
#concatenate 2 array along the first axis
dim_2 = np.array([[2, 3, 4], [4, 1, 2]])
np.concatenate([dim_2, dim_2])

array([[2, 3, 4],
       [4, 1, 2],
       [2, 3, 4],
       [4, 1, 2]])

In [4]:
#concanate 2 array along the second axis
np.concatenate([dim_2, dim_2], axis=1)

array([[2, 3, 4, 2, 3, 4],
       [4, 1, 2, 4, 1, 2]])

In [11]:
#split to 2 array by row
upper, lower = np.vsplit(dim_2, [1])
print(upper)
print(lower)

[[2 3 4]]
[[4 1 2]]


In [13]:
#split to 2 array by column
left, right = np.hsplit(dim_2, [1])
print(left)
print(right)

[[2]
 [4]]
[[3 4]
 [1 2]]


<h3> UFuncs <h3>

In [19]:
#use ufuncs to work faster
theta = np.linspace(0, np.pi, 3)
print(theta)

[0.         1.57079633 3.14159265]


In [20]:
print(np.cos(theta))
print(np.sin(theta))
print(np.tan(theta))

[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [23]:
m = [1, 2.71, 3.14, 10]
print(np.log(m))
print(np.log2(m))
print(np.log10(m))

[0.         0.99694863 1.1442228  2.30258509]
[0.         1.43829285 1.65076456 3.32192809]
[0.         0.43296929 0.49692965 1.        ]


In [26]:
from scipy import special
m = [1, 5, 10]
print(special.gamma(m))
print(special.gammaln(m))
print(special.beta(2, m))

[1.0000e+00 2.4000e+01 3.6288e+05]
[ 0.          3.17805383 12.80182748]
[0.5        0.03333333 0.00909091]


In [35]:
#Don't need the temperatory array
x = np.linspace(1, 6, 2)
y = np.empty(2)
np.multiply(x, 4, out=y)
print(y)

[ 4. 24.]
