In [1]:
import numpy as np

<h3>Array concatenation and splitting<h3>

In [4]:
x = np.array([3, 2, 1])
y = np.array([1, 2, 3])
np.concatenate([x, y])

array([3, 2, 1, 1, 2, 3])

In [6]:
#concatenate 2 array along the first axis
dim_2 = np.array([[2, 3, 4], [4, 1, 2]])
np.concatenate([dim_2, dim_2])

array([[2, 3, 4],
       [4, 1, 2],
       [2, 3, 4],
       [4, 1, 2]])

In [7]:
#concanate 2 array along the second axis
np.concatenate([dim_2, dim_2], axis=1)

array([[2, 3, 4, 2, 3, 4],
       [4, 1, 2, 4, 1, 2]])